# Generated by Django 4.2.2 on 2023-06-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('IFSC', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Branch', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Contact', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('BankName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
            ],
        ),
    ]
